apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: messaging-service
        image: nginx:alpine
